# Generated by Django 4.0.1 on 2022-02-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='about_author',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
