# Generated by Django 4.0.1 on 2022-02-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_about_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='about_author',
        ),
    ]
