# Generated by Django 4.0.1 on 2022-02-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={},
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='description',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='post_date',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='blog',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='author',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
